"""Export: JSON summaries, CSV tables, and self-contained HTML reports."""

from __future__ import annotations

import csv
import json
from typing import Any, Dict, Optional

import numpy as np


def _jsonify(obj: Any) -> Any:
    """Recursively convert numpy types so json.dump succeeds."""
    if isinstance(obj, dict):
        return {str(k): _jsonify(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonify(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.floating, np.integer)):
        return obj.item()
    if isinstance(obj, float) and (np.isnan(obj) or np.isinf(obj)):
        return str(obj)
    if hasattr(obj, "to_dict"):
        return _jsonify(obj.to_dict())
    return obj


def to_json(obj: Any, path: str, indent: int = 2) -> str:
    """Write any nngeom result (dict / dataclass with to_dict) to JSON."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(_jsonify(obj), f, indent=indent)
    return path


def to_csv(table: Dict[str, Dict[str, float]], path: str) -> str:
    """Write a nested dict {row: {col: value}} as CSV (e.g. layer drift)."""
    rows = list(table.keys())
    cols = sorted({c for r in table.values() for c in r})
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["name"] + cols)
        for r in rows:
            writer.writerow([r] + [table[r].get(c, "") for c in cols])
    return path


_HTML_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #222; }}
h1 {{ border-bottom: 2px solid #4a6fa5; padding-bottom: .3rem; }}
h2 {{ color: #4a6fa5; margin-top: 2rem; }}
table {{ border-collapse: collapse; margin: .5rem 0; }}
td, th {{ border: 1px solid #ccc; padding: .3rem .7rem; text-align: left; font-size: .9rem; }}
th {{ background: #f0f4f8; }}
.warn {{ background: #fff3cd; border-left: 4px solid #e0a800; padding: .5rem 1rem; margin: .5rem 0; }}
.figure {{ margin: 1rem 0; }} img {{ max-width: 100%; }}
pre {{ background: #f6f8fa; padding: .7rem; overflow-x: auto; }}
footer {{ margin-top: 3rem; color: #888; font-size: .8rem; }}
</style></head><body>
<h1>{title}</h1>
{body}
<footer>Generated by nngeom</footer>
</body></html>
"""


def _dict_to_table(d: Dict) -> str:
    rows = "".join(
        f"<tr><th>{k}</th><td>{f'{v:.6g}' if isinstance(v, float) else v}</td></tr>"
        for k, v in d.items()
        if not isinstance(v, (dict, list, np.ndarray))
    )
    return f"<table>{rows}</table>" if rows else ""


def _fig_to_base64(fig) -> str:
    import base64
    import io

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def report_html(report, path: str, title: Optional[str] = None) -> str:
    """Render a GeometryReport (or plain dict of sections) to standalone HTML.

    Embeds figures as base64 PNGs when matplotlib is available, so the file
    is fully self-contained and shareable.
    """
    from .utils import HAS_MATPLOTLIB

    sections = report.sections if hasattr(report, "sections") else dict(report)
    warnings = getattr(report, "warnings", [])
    figures = getattr(report, "figures", {})

    parts = []
    if warnings:
        parts.append("<h2>Warnings</h2>")
        for w in warnings:
            parts.append(f'<div class="warn">{w}</div>')
    for name, content in sections.items():
        parts.append(f"<h2>{name.replace('_', ' ').title()}</h2>")
        if isinstance(content, dict):
            parts.append(_dict_to_table(content))
            for sub_name, sub in content.items():
                if isinstance(sub, dict):
                    parts.append(f"<h3>{sub_name}</h3>")
                    parts.append(_dict_to_table(sub))
        else:
            parts.append(f"<pre>{content}</pre>")
    if HAS_MATPLOTLIB and figures:
        parts.append("<h2>Figures</h2>")
        for fig_name, fig in figures.items():
            parts.append(
                f'<div class="figure"><h3>{fig_name}</h3>'
                f'<img alt="{fig_name}" src="data:image/png;base64,{_fig_to_base64(fig)}"></div>'
            )
    html = _HTML_TEMPLATE.format(title=title or getattr(report, "title", "nngeom Geometry Report"),
                                 body="\n".join(parts))
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path
